//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public string GroupId { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
        public string RoleId { get; set; }
        public string SiteId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Site Site { get; set; }
    }
}
