//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserByGroup
    {
        public string GroupId { get; set; }
        public string GroupName { get; set; }
        public string Description { get; set; }
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public string SiteId { get; set; }
        public string SiteName { get; set; }
        public string UserId { get; set; }
        public string Nuid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
    }
}
